batch_size:
  bronze:
    accounts: 10000
    transactions: 50000
    customers: 10000
  silver:
    accounts: 10000
    transactions: 50000
    customers: 10000
  gold:
    accounts: 10000
    transactions: 50000
    customers: 10000
